travis:
  secure:
    BINSTAR_TOKEN: isFPaBiERpeMe2dVrHFwIHfHSJM/3N6KWklnKsuqECcEPrKeRTkcAFaNW7I3U3VefnujwLFGjy/fDBnqkrfYCYy/oUiDaW3A0hrF7g61OSj8LPdpxHrZ1vDT3cUK0sgm/vm+W1oW89GD4Aoq5ETM/BCl91NEB+NedOVRBzNQw/dGrFUG5sIkZoYWIc/TM1N6pj1DjfbBdtv/56es9l7lG7mWwE9L1aFBiY6QF7DLP7DZINQvUlcU55mvlRtUO8PTFPoJaYYlhRtljpFuxk7iYS3Bvs1ARizLV1OFFWs/vAmtW+TuTSdD7XI/NnjXrbRIaqaofd/K6WfkVjLJQxkzOI6hUz99uRqv7F/2HV+X1aMgHStibWbalH+P7KiXW5/FKxaeP03T824Bh3TttcL4BzCATxJ4GfDcnLDHoYNTwJd3eTN1ZYqV4sWuXNXkOYMsiyPP+ajvm2coATPLmr2dAIbXSeyPzbjLYOv5YBJ4CSJ7ySvm6T+63CkcAhMLot2elLZp44ir1ZIX9QyVhyo8u/qyl0r+4WNzrk6B3LYQWh/UyNXDT6r/YQop02Qn6qfRFPy5/6P3xxC5jO9Wr863ls2HLaFU5TwuuGUxg7Subgp23arUYgkrIPNr7lPslF0+IMeCVAoGVhVm7DwckqYGqqlpqNtHibHmbdGVyIipruU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
